<a href="https://colab.research.google.com/github/bharatkaushik2015/Python-library-practice-notes/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**
<br>
1. n-dimensional array or ndarrays
<br>
2. each data element is of fixed size and same data type

In [1]:
# creating 1-D list
import numpy as np
lst=[1,2,3,5,10]
arr=np.array(lst)
arr

array([ 1,  2,  3,  5, 10])

In [2]:
type(arr)

numpy.ndarray

In [3]:
# creating 2-D list
lst1=[[1,2,3],[4,5,6]]
arr_2d=np.array(lst1)
arr_2d


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
type(arr_2d)

numpy.ndarray

**ndarray Attributes**

1. ndim : Returns number of dimensions.

2. shape: Returns Shape in tuple.

3. size : Total number of elements.

4. dtype : Type of each element.

5. itemsize : Size of each element in Bytes.

6. nbytes : Total bytes consumed by all elements.







In [5]:
arr.ndim # returns number of dimensions

1

In [6]:
arr_2d.ndim

2

In [7]:
arr.shape # shape in tuples

(5,)

In [8]:
arr_2d.shape

(2, 3)

In [9]:
arr.size # total number of elements

5

In [10]:
arr_2d.size

6

In [11]:
arr.dtype # type of each elements

dtype('int64')

In [12]:
arr_2d.dtype

dtype('int64')

In [13]:
arr.itemsize #size of each elements in bytes

8

In [14]:
arr_2d.itemsize

8

In [15]:
arr.nbytes # Total bytes consumed by all elements

40

In [16]:
arr_2d.nbytes

48

In [17]:
y=np.array([[2,4,6],[6,7,8]], dtype="float64")
y.dtype

dtype('float64')

**Numpy array creation**
1. From Python built-in datatypes : lists or tuples

2. Using Numpy array creation methods like ones, ones_like, zeros, zeros_like

3. Using Numpy numeric sequence generators.

4. Using Numpy random module.

5. By reading data from a file.

In [18]:
a=[i for i in range(10) if i%2!=0]
a

[1, 3, 5, 7, 9]

In [19]:
ar=np.array(a) # created array using list
ar

array([1, 3, 5, 7, 9])

In [20]:
b=(1,2,3)
br=np.array(b) # created array using tuple
br

array([1, 2, 3])

In [21]:
np.empty([4,4]) # creates empty array with random values

array([[4.84254362e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [22]:
np.empty_like(arr)

array([98014175423808,              0,              0,              0,
                   48])

In [23]:
np.eye(2) # identity matrix (2x2)

array([[1., 0.],
       [0., 1.]])

In [24]:
np.eye(3,k=1) # identity matrix (3x3) -- k argument shits the ones above and below with negative values

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [25]:
np.identity(3) # identity matrix (3x3) -- only middle diagonal

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.ones(5) # create arrays with ones default datatpe float64

array([1., 1., 1., 1., 1.])

In [27]:
np.ones((5,1), dtype="int64")

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [28]:
np.ones_like(arr_2d)

array([[1, 1, 1],
       [1, 1, 1]])

In [29]:
np.zeros((3,3)) # create arrays with zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.zeros_like(arr)

array([0, 0, 0, 0, 0])

In [31]:
np.full(shape=(2,3),fill_value=10) # gives an array with filled value

array([[10, 10, 10],
       [10, 10, 10]])

In [32]:
# Numeric sequence generator


In [33]:
np.arange(10) # return evenly spaced array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(2,10,0.9) # main difference from regaular range function is that it supports float values in steps

array([2. , 2.9, 3.8, 4.7, 5.6, 6.5, 7.4, 8.3, 9.2])

In [36]:
np.linspace(2,10, num=20) # syntax [start,stop] evenly spaced array

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [37]:
np.linspace(2,10, num=20, endpoint=False) # endpoint excluded in arange it's excluded by default

array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6, 6. , 6.4, 6.8,
       7.2, 7.6, 8. , 8.4, 8.8, 9.2, 9.6])

In [38]:
# Random numbers generator

In [39]:
np.random.seed(42)
np.random.rand(10) # 10 random numbers between 0 and 1

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [40]:
def random_generator():
    np.random.seed(42)
    cr=np.random.rand(5)
    return cr

random_generator()

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [41]:
random_generator() # shows that seed value helps in regenerating same values everytime

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [42]:
np.random.randint(10,100,10) # 10 random integers between 10 and 100

array([92, 96, 84, 84, 97, 33, 12, 31, 62, 11])

randn is used to simulate random normal distribution

In [43]:
np.random.randn(10) # 10 random numbers from normal distribution

array([ 0.23309524,  0.11799461,  1.46237812,  1.53871497, -2.43910582,
        0.60344123, -0.25104397, -0.16386712, -1.47632969,  1.48698096])

In [44]:
10+2*np.random.randn(10) # random normal distribution with mu=10 and sigma=2

array([ 9.95108965, 10.71110263, 10.83402222, 11.66492371,  9.41320171,
        9.94032286, 10.19025157, 11.32930869,  9.71956301,  9.9336132 ])

In [45]:
np.random.rand(3,3)

array([[0.23089383, 0.24102547, 0.68326352],
       [0.60999666, 0.83319491, 0.17336465],
       [0.39106061, 0.18223609, 0.75536141]])

In [46]:
np.random.random((3,2)) # take tuple as argument

array([[0.42515587, 0.20794166],
       [0.56770033, 0.03131329],
       [0.84228477, 0.44975413]])

**ARRAY SHAPE MANIPULATION**

In [47]:
np.random.seed(42)
arr_m=np.random.randn(10)

In [48]:
arr_m

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004])

In [49]:
arr_m.reshape(2,5) # reshape array

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004]])

stacking arrays vertically (np.vstack)

In [50]:
arr_m2=np.linspace(1,10,num=10).reshape(2,5)
arr_m2

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [51]:
arr_m3=np.arange(1,11,dtype=float).reshape(2,5)
arr_m3

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [52]:
np.vstack((arr_m2,arr_m3))

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [53]:
x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
np.vstack((x,y))

array([[-1,  1],
       [-3,  3],
       [-2,  2],
       [-4,  4]])

Stacking arrays horizontally (np.hstack)

In [54]:
x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
z = np.array([[-5, 5], [-6, 6]])

In [55]:
x

array([[-1,  1],
       [-3,  3]])

In [56]:
y

array([[-2,  2],
       [-4,  4]])

In [57]:
np.hstack((x,y,z))

array([[-1,  1, -2,  2, -5,  5],
       [-3,  3, -4,  4, -6,  6]])

Splitting arrays vertically (np.vsplit)

In [58]:
arr_m4=np.arange(30)
arr_m4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [59]:
arr_m5= arr_m4.reshape(6,5)

In [60]:
np.vsplit(arr_m5,2)[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
np.vsplit(arr_m5,2)[1]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [62]:
# can split vertically at specific row number

x = np.arange(40).reshape(8, 5)
res = np.vsplit(x, (2, 6))
print(res[0], end='\n\n')
print(res[1], end='\n\n')
print(res[2])

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[30 31 32 33 34]
 [35 36 37 38 39]]


splitting arrays horizontally

In [63]:
x = np.arange(40).reshape(8, 5)
res = np.hsplit(x, (2, 4))
print(res[0], end='\n\n')
print(res[1], end='\n\n')
print(res[2])

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]
 [25 26]
 [30 31]
 [35 36]]

[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]
 [27 28]
 [32 33]
 [37 38]]

[[ 4]
 [ 9]
 [14]
 [19]
 [24]
 [29]
 [34]
 [39]]


In numpy when we cut ndarray
1. row-wise we call it vertical split
2. column-wise we call it horizontal split  


**Basic Operations in Numpy**
1. numpy ndarray supports operations element wise
2. Operations between arrays also happens elements wise

In [64]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a+10 # scalar addition

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [66]:
a*2 # scalar multiplication

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [67]:
a/2 # scalar division

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [68]:
a-2 # scalar subtraction

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [69]:
b=np.arange(0,20,2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [70]:
a+b # addition of two arrays

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [71]:
a-b

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [72]:
a*b

array([  0,   2,   8,  18,  32,  50,  72,  98, 128, 162])

In [73]:
a/b

<ipython-input-73-aae42d317509>:1: RuntimeWarning: invalid value encountered in divide
  a/b


array([nan, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])

**Broadcasting in NumPy**
<br>
Element wise operations between arrays are possible only when they have the same shape or compatible for Broadcasting.
<br>
Steps followed to verify the feasibility of Broadcasting between arrays are:
1. Initially, compare the dimensions of all arrays.
2. If dimensions do not match, prepend 1's to shape of a smaller array so that it matches dimensions of a larger array.
3. Start comparing array shapes from the last dimension and move backward.
4. If the shape of both arrays are equal or either of it has a shape of 1, continue the comparison.
5. Else at any dimension, if step 4 fails, broadcasting between arrays is not feasible.

Finally, the resulted broadcasting array shape would be maximum of two compared shapes in each dimension.


Given: s1 = (4, 3); s2 = (3,)
Step 1 and 2: s1 = (4, 3); s2 = (1, 3)
Step 3 and 4: pass in 2 dimensions
Result : Broadcasting feasible;
         resulted array shape - (4,3)

**Numpy Universal Functions**

In [74]:
# Examples

In [75]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.max(a) # max value

9

In [77]:
np.min(a) # min value

0

In [78]:
np.mean(a)

4.5

In [79]:
np.sum(a) # sum of all elements

45

In [80]:
np.median(a) # median

4.5

In [81]:
a.mean() # mean

4.5

In [82]:
a.std()

2.8722813232690143

In [83]:
np.std(a) # standard deviation

2.8722813232690143

In [84]:
np.square(a)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [85]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [86]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [87]:
np.e # euler's constant value

2.718281828459045

applying these functions on elements along some axis

In [88]:
c=np.arange(20).reshape(2,2,5)

In [89]:
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [90]:
np.sum(c,axis=0) # sum along depth of the 3d structure

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [91]:
np.sum(c, axis=1) # sum along height of the 3d structure

array([[ 5,  7,  9, 11, 13],
       [25, 27, 29, 31, 33]])

In [92]:
np.sum(c, axis=2) # sum along width of the 3d structure

array([[10, 35],
       [60, 85]])

In [93]:
np.sum(c) # sum of all elements

190

Indexing & Slicing 1-d ndarray

In [94]:
# slice object -> start:end:stop (all three optional)
x = np.array([5, 10, 15, 20, 25, 30, 35])
print(x[1])  # Indexing
print(x[1:6]) # Slicing
print(x[1:6:3]) # Slicing

10
[10 15 20 25 30]
[10 25]


Indexing & Slicing 2-d ndarray

In [95]:
# syntax arr[slicing_object1,slicing_object2] or arr[row_object,column_object]
import numpy as np
y = np.array([[0, 1, 2],
              [3, 4, 5]])
print(y[1:2, 1:3])
print(y[1])
print(y[:, 1])

[[4 5]]
[3 4 5]
[1 4]
[[4 5]]
[3 4 5]
[1 4]


In [97]:
z = np.array([[[-1, 1], [-2, 2]],
              [[-4, 4], [-5, 5]],
              [[-7, 7], [-9, 9]]])
z

array([[[-1,  1],
        [-2,  2]],

       [[-4,  4],
        [-5,  5]],

       [[-7,  7],
        [-9,  9]]])

In [98]:
z[1,:,1]

array([4, 5])

In [99]:
print(z[1:,1,:])

[[-5  5]
 [-9  9]]


In [100]:
z[2]

array([[-7,  7],
       [-9,  9]])

Loop over for ndarray

In [101]:
z

array([[[-1,  1],
        [-2,  2]],

       [[-4,  4],
        [-5,  5]],

       [[-7,  7],
        [-9,  9]]])

In [104]:
for r in z:
    print(r, end="\n\n")

[[-1  1]
 [-2  2]]

[[-4  4]
 [-5  5]]

[[-7  7]
 [-9  9]]



In [107]:
#np.nditer
for r in np.nditer(z):
    print(r, end=" ")

-1 1 -2 2 -4 4 -5 5 -7 7 -9 9 

In [110]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [115]:
x[[0,1,2],[0,1,1]]

array([1, 4, 6])

In [119]:
x.sum(-1) # sum across axis=1 Negative axis: 1d - 0|-1, 2d-(axis=0|-2-r,axis=1|-1-c)

array([ 3,  7, 11])

Some other very important functions

In [120]:
# np.any and np.all
x = np.array([1, 0, 0])
print(np.any(x)) # Any one element True
print(np.all(x))

True
False


In [123]:
np.any([np.nan,0])

True

In [124]:
np.any([np.inf,0])

True

In [125]:
np.all([1.0, np.nan])

True

NOTE: np.nan. np.inf gives true because they are not equal to true

In [128]:
d=np.linspace(1,10, num=10).reshape(5,2)
d

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [130]:
d.transpose()

array([[ 1.,  3.,  5.,  7.,  9.],
       [ 2.,  4.,  6.,  8., 10.]])

In [131]:
d.T

array([[ 1.,  3.,  5.,  7.,  9.],
       [ 2.,  4.,  6.,  8., 10.]])

In [133]:
d.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [134]:
d.ravel()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [135]:
np.ravel(d)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Other important functions are:
1. np.sort()
2. np.argsort()
3. np.argmax()
4. np.unique()
5. np.where(condition, True_value,false_value)

In [136]:
np.random.seed(42)
e=np.random.randint(40,80,10)
e

array([78, 68, 54, 47, 60, 78, 58, 62, 50, 50])

In [137]:
np.sort(e)

array([47, 50, 50, 54, 58, 60, 62, 68, 78, 78])

In [140]:
np.argsort(e) # gives indices in sorted manner

array([3, 8, 9, 2, 6, 4, 7, 1, 0, 5])

In [142]:
np.argmax(e)

0

In [143]:
np.argmin(e)

3

In [144]:
f=np.array([1,2,3,3,4,4])
np.unique(f)

array([1, 2, 3, 4])

In [146]:
np.where(f==3,f+1,f)

array([1, 2, 4, 4, 4, 4])

In [153]:
d_2=np.vsplit(d,(4,5))[0]
d_3=np.hsplit(d_2.reshape(2,4),2)[0]

In [156]:
d_3

array([[1., 2.],
       [5., 6.]])

In [155]:
np.rot90(d_3) # rotates matrix anti-clockwise

array([[2., 6.],
       [1., 5.]])